from django.urls import include, path

from .views import authViews, dataViews, formViews
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', dataViews.index, name='index'),
    path('addDepartment', formViews.addDepartment, name='addDepartment'),
    path('login', auth_views.LoginView.as_view(template_name='auth_templates/login.html'), name = 'login'),
    path('logout', authViews.logout_view, name = 'logout'),
    path('register', authViews.register, name = 'register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('successPage', authViews.successPage, name="successPage"),
    path('passwordReset', authViews.passwordReset, name="passwordReset"),
    path('reset/<uidb64>/<token>', authViews.passwordResetConfirm, name="passwordResetConfirm"),
    path('activate/<uidb64>/<token>', authViews.activate, name='activate'),
    path('addTeacher/<int:department>', formViews.addTeacher, name='addTeacher'),
    path('addTeacher/<int:department>/<int:id>', formViews.addTeacher, name='addTeacher'),
    path('getTeacher/<int:id>/<int:timetableId>', dataViews.getTeacher, name='getTeacher'),
    path('setAvailability/<int:teacherid>', formViews.setAvailability, name='setAvailability'),
    path('addModule/<int:yearId>', formViews.addModule, name="addModule"),
    path('addModule/<int:yearId>/<int:parentId>', formViews.addModule, name="addModule"),
    path('addYear/<int:departmentId>', formViews.addYear, name="addYear"),
    path('addYear', formViews.addYear, name="addYear"),
    path('getModules/<int:groupId>', dataViews.getModules, name='getModules'),
    path('getModules/<int:groupId>/<int:timetableId>', dataViews.getModules, name='getModules'),
    path('getModules', dataViews.getModules, name='getModules'),
    path('assignTeacher/<int:departmentId>/<int:moduleId>', formViews.assignTeacher, name='assignTeacher'),
    path('assignPeriod/<int:department>/<int:groupId>', formViews.assignPeriod, name='assignPeriod'),
    path('deleteObject/<str:type>/<str:id>', formViews.deleteObject, name='deleteObject'),
    path('combing/<int:timetableId>', dataViews.combingView, name="combingView"),
    path('combing/<int:timetableId>/<str:groupByClass>', dataViews.combingView, name="combingView"),
    path('calendar/<int:timetableId>', dataViews.calendarView, name="calendarView"),
    path('calendar/<int:timetableId>/<int:teacherId>', dataViews.calendarView, name="calendarView"),
    path('calendarPeriodDrop/<str:day>/<int:week>/<int:groupId>', formViews.calendarPeriodDrop, name="calendarPeriodDrop"),
    #path('getCalendarData/<int:timetableId>', dataViews.getCalendarData, name='getCalendarData'),
    path('addModuleCalendar/<str:day>/<int:week>/<int:timetableId>', formViews.addModuleCalendar, name='addModuleCalendar' ),
    #path('getCalendar/<int:timetableId>/<int:teacherId>', dataViews.getCalendar, name="getCalendar"),
    path('assignTeacherCombing/<int:teacherId>/<int:timetableId>', formViews.assignTeacherCombing, name='assignTeacherCombing'),
    path('unassignTeacher/<int:modId>', formViews.unassignTeacher, name="unassignTeacher"),
    path('assignTeacherDrop/<int:teacherId>/<int:modId>', formViews.assignTeacherDrop, name="assignTeacherDrop"),
    path('changeColor/<int:parentId>', formViews.changeColor, name='changeColor'),
    path('dashboard', dataViews.dashboard, name="dashboard"),
    path('displayDashboardContent/<int:timetableId>', dataViews.displayDashboardContent, name='displayDashboardContent'),
    path('getList/<str:type>/<int:timetableId>', dataViews.getList, name='getList'),
    path('getSidebar/<str:type>/<int:timetableId>', dataViews.getSidebar, name='getSidebar'),
    path('changeTheme/<str:theme>', formViews.changeTheme, name='changeTheme'),
    path('changeTheme/<str:theme>/<int:timetableId>', formViews.changeTheme, name='changeTheme'),
    path('addTimetable/<int:yearId>', formViews.addTimetable, name="addTimetable"),
    path('addTimetable/<int:yearId>/<int:timetableId>', formViews.addTimetable, name="addTimetable"),
    path('wizard/<int:timetableA>', formViews.timetableWizard, name='timetableWizard'),
    path('cspAutoAssign/<int:timetableA>', dataViews.cspAutoAssign, name='cspAutoAssign'),
    path('preferences/<int:teacherId>/<int:timetableId>', dataViews.teacherPreferences, name='preferences'),
    path('addPreferences/<int:teacherId>/<int:timetableId>', formViews.addPreference, name='addPreference'),
    path('getGroups/<int:parentId>', dataViews.getGroups, name="getGroups"),
    path('getModulesJson/<int:groupId>', dataViews.getModulesJson, name="getModulesJson"),
    path('getGroups/<int:parentId>/<str:combing>', dataViews.getGroups, name="getGroups"),
    path('getModulesJson/<int:groupId>/<str:combing>', dataViews.getModulesJson, name="getModulesJson"),
    path('timetableLanding/<int:timetableId>', dataViews.displayTimetableLanding, name="timetableLanding"),
    path('departmentInfo/<int:departmentId>', dataViews.departmentInfo, name='departmentInfo'),
    path('editDepartment/<int:departmentId>', formViews.editDepartment, name='editDepartment'),
    path('setDefaultTimetable/<int:yearId>/<int:timetableId>', formViews.setDefaultTimetable, name="setDefaultTimetable"),
    path('templateBuilder/<int:timetableId>', formViews.templateBuilder, name='templateBuilder'),
    path('templateBuilderInstructions/<int:timetableId>', formViews.templateBuilderInstructions, name='templateBuilderInstructions'),
    path('templateBuilderDownload/<int:timetableId>/<str:choices>', formViews.templateBuilderDownload, name='templateBuilderDownload'),
    path('uploadTest/<int:timetableId>', formViews.getTemplateFileTest, name="uploadTest"),
    path('exportCalendar/<int:timetableId>', dataViews.exportCalendarView, name='exportCalendar'),
    path('exportCalendar/<int:timetableId>/<int:teacherId>', dataViews.exportCalendarView, name='exportCalendar'),
    path('exportCombing/<int:timetableId>', dataViews.exportCombingView, name="exportCombing")
    ]